<template>
  <div>ここにタスクリストを出すよ～</div>
  <ul id="example-1">
    <li v-for="tasks in task" :key="task.id">{{ task.id }}: {{ task.name }}</li>
  </ul>
</template>

<script>
module.exports = {
  data() {
    return {
      tasks: [
        { name: "Debut", owner: 1 },
        { name: "Search Mission", owner: 1 },
        { name: "Checking", owner: 1 },
        { name: "Shootout Picnic", owner: 1 },
        { name: "Delivery from the past", owner: 1 },
        { name: "BP Depot", owner: 1 },
        { name: "The Bunker - Part 1", owner: 1 },
        { name: "The Bunker - Part 2", owner: 1 },
        { name: "Bad Rep Evidence", owner: 1 },
        { name: "Ice Cream Cones", owner: 1 },
        { name: "No Place for Renegades", owner: 1 },
        { name: "Documents", owner: 1 },
        { name: "Postman Pat - Part 1", owner: 1 },
        { name: "You've Got Mail", owner: 1 },
        { name: "Glory to CPSU - Part 1", owner: 1 },
        { name: "Glory to CPSU - Part 2", owner: 1 },
        { name: "Shaking up the Teller", owner: 1 },
        { name: "The Punisher - Part 1", owner: 1 },
        { name: "The Punisher - Part 2", owner: 1 },
        { name: "The Punisher - Part 3", owner: 1 },
        { name: "The Punisher - Part 4", owner: 1 },
        { name: "The Punisher - Part 5", owner: 1 },
        { name: "Kings of the Rooftops", owner: 1 },
        { name: "Best Job in the World", owner: 1 },
        { name: "The Punisher - Part 6", owner: 1 },
        { name: "Green Corridor", owner: 1 },
        { name: "Anesthesia", owner: 1 },
        { name: "Grenadier", owner: 1 },
        { name: "Test Drive - Part 1", owner: 1 },
        { name: "Test Drive - Part 2", owner: 1 },
        { name: "Test Drive - Part 3", owner: 1 },
        { name: "Perfect Mediator", owner: 1 },
        { name: "Polikhim Hobo", owner: 1 },
        { name: "Regulated Materials", owner: 1 },
        { name: "Big Customer", owner: 1 },
        { name: "No Offence", owner: 1 },
        { name: "Capturing Outposts", owner: 1 },
        { name: "Intimidator", owner: 1 },
        { name: "Escort", owner: 1 },
        { name: "Easy Job - Part 1", owner: 1 },
        { name: "Easy Job - Part 2", owner: 1 },
        { name: "Our Own Land", owner: 1 },
        { name: "Reconnaissance", owner: 1 },
        { name: "Gendarmerie - Mall Cop", owner: 1 },
        { name: "Gendarmerie - District Patrol", owner: 1 },
        { name: "Shortage", owner: 2 },
        { name: "Operation Aquarius - Part 1", owner: 2 },
        { name: "Operation Aquarius - Part 2", owner: 2 },
        { name: "Sanitary Standards - Part 1", owner: 2 },
        { name: "Sanitary Standards - Part 2", owner: 2 },
        { name: "Painkiller", owner: 2 },
        { name: "Pharmacist", owner: 2 },
        { name: "Population Census", owner: 2 },
        { name: "Urban Medicine", owner: 2 },
        { name: "Car Repair", owner: 2 },
        { name: "Hippocratic Oath", owner: 2 },
        { name: "Disease History", owner: 2 },
        { name: "Supply Plans", owner: 2 },
        { name: "Dangerous Road", owner: 2 },
        { name: "Health Care Privacy - Part 1", owner: 2 },
        { name: "Health Care Privacy - Part 2", owner: 2 },
        { name: "Health Care Privacy - Part 3", owner: 2 },
        { name: "An Apple a Day Keeps the Doctor Away", owner: 2 },
        { name: "Health Care Privacy - Part 4", owner: 2 },
        { name: "Athlete", owner: 2 },
        { name: "Private Clinic", owner: 2 },
        { name: "Health Care Privacy - Part 5", owner: 2 },
        { name: "Decontamination Service", owner: 2 },
        { name: "General Wares", owner: 2 },
        { name: "Colleagues - Part 1", owner: 2 },
        { name: "Colleagues - Part 2", owner: 2 },
        { name: "Colleagues - Part 3", owner: 2 },
        { name: "Postman Pat - Part 2", owner: 2 },
        { name: "Out of Curiosity", owner: 2 },
        { name: "Trust Regain", owner: 2 },
        { name: "Crisis", owner: 2 },
        { name: "Seaside Vacation", owner: 2 },
        { name: "Lost Contact", owner: 2 },
        { name: "Drug Trafficking", owner: 2 },
        { name: "Pets Won't Need It", owner: 2 },
        { name: "Ambulances Again", owner: 2 },
        { name: "Collector", owner: 3 },
        { name: "The Choice", owner: 3 },
        { name: "SkierFullRes.jpg", owner: 4 },
        { name: "Supplier", owner: 4 },
        { name: "The Extortionist", owner: 4 },
        { name: "Stirrup", owner: 4 },
        { name: "What’s on the Flash Drive?", owner: 4 },
        { name: "Golden Swag", owner: 4 },
        { name: "Chemical - Part 1", owner: 4 },
        { name: "Chemical - Part 2", owner: 4 },
        { name: "Chemical - Part 3", owner: 4 },
        { name: "Chemical - Part 4", owner: 4 },
        { name: "Loyalty Buyout", owner: 4 },
        { name: "Vitamins - Part 1", owner: 4 },
        { name: "Vitamins - Part 2", owner: 4 },
        { name: "Friend from the West - Part 1", owner: 4 },
        { name: "Friend from the West - Part 2", owner: 4 },
        { name: "Informed Means Armed", owner: 4 },
        { name: "Chumming", owner: 4 },
        { name: "Debtor", owner: 4 },
        { name: "House Arrest - Part 1", owner: 4 },
        { name: "House Arrest - Part 2", owner: 4 },
        { name: "Silent Caliber", owner: 4 },
        { name: "Bullshit", owner: 4 },
        { name: "Setup", owner: 4 },
        { name: "Flint", owner: 4 },
        { name: "Lend-Lease - Part 1", owner: 4 },
        { name: "Kind of Sabotage", owner: 4 },
        { name: "Rigged Game", owner: 4 },
        { name: "Safe Corridor", owner: 4 },
        { name: "Night Sweep", owner: 4 },
        { name: "Long Road", owner: 4 },
        { name: "Missing Cargo", owner: 4 },
        { name: "Top Secret", owner: 4 },
        { name: "Beyond the Red Meat - Part 1", owner: 4 },
        { name: "Beyond the Red Meat - Part 2", owner: 4 },
        { name: "Fishing Gear", owner: 5 },
        { name: "Tigr Safari", owner: 5 },
        { name: "Scrap Metal", owner: 5 },
        { name: "Eagle Eye", owner: 5 },
        { name: "Humanitarian Supplies", owner: 5 },
        { name: "The Cult - Part 1", owner: 5 },
        { name: "The Cult - Part 2", owner: 5 },
        { name: "Spa Tour - Part 1", owner: 5 },
        { name: "Spa Tour - Part 2", owner: 5 },
        { name: "Spa Tour - Part 3", owner: 5 },
        { name: "Spa Tour - Part 4", owner: 5 },
        { name: "Spa Tour - Part 5", owner: 5 },
        { name: "Spa Tour - Part 6", owner: 5 },
        { name: "Spa Tour - Part 7", owner: 5 },
        { name: "Road Closed", owner: 5 },
        { name: "Cargo X - Part 1", owner: 5 },
        { name: "Cargo X - Part 2", owner: 5 },
        { name: "Cargo X - Part 3", owner: 5 },
        { name: "Cargo X - Part 4", owner: 5 },
        { name: "Insomnia", owner: 5 },
        { name: "Your Car Needs a Service", owner: 5 },
        { name: "Wet Job - Part 1", owner: 5 },
        { name: "Wet Job - Part 2", owner: 5 },
        { name: "Wet Job - Part 3", owner: 5 },
        { name: "Wet Job - Part 4", owner: 5 },
        { name: "Wet Job - Part 5", owner: 5 },
        { name: "Worst Job in the World", owner: 5 },
        { name: "Mentor", owner: 5 },
        { name: "Wet Job - Part 6", owner: 5 },
        { name: "The Guide", owner: 5 },
        { name: "Samples", owner: 5 },
        { name: "TerraGroup Employee", owner: 5 },
        { name: "Lend-Lease - Part 2", owner: 5 },
        { name: "Peacekeeping Mission", owner: 5 },
        { name: "Classified Technologies", owner: 5 },
        { name: "Revision - Reserve", owner: 5 },
        { name: "Revision - Lighthouse", owner: 5 },
        { name: "Revision - Streets of Tarkov", owner: 5 },
        { name: "The Cleaner", owner: 5 },
        { name: "Special Equipment", owner: 5 },
        { name: "Counteraction", owner: 5 },
        { name: "Overpopulation", owner: 5 },
        { name: "Trophies", owner: 5 },
        { name: "Introduction", owner: 6 },
        { name: "Gunsmith - Part 1", owner: 6 },
        { name: "Gunsmith - Part 2", owner: 6 },
        { name: "Gunsmith - Part 3", owner: 6 },
        { name: "Gunsmith - Part 4", owner: 6 },
        { name: "Gunsmith - Part 5", owner: 6 },
        { name: "Gunsmith - Part 6", owner: 6 },
        { name: "Gunsmith - Part 7", owner: 6 },
        { name: "Gunsmith - Part 8", owner: 6 },
        { name: "Gunsmith - Part 9", owner: 6 },
        { name: "Gunsmith - Part 10", owner: 6 },
        { name: "Gunsmith - Part 11", owner: 6 },
        { name: "Gunsmith - Part 12", owner: 6 },
        { name: "Gunsmith - Part 13", owner: 6 },
        { name: "Gunsmith - Part 14", owner: 6 },
        { name: "Gunsmith - Part 15", owner: 6 },
        { name: "Gunsmith - Part 16", owner: 6 },
        { name: "Gunsmith - Part 17", owner: 6 },
        { name: "Gunsmith - Part 18", owner: 6 },
        { name: "Gunsmith - Part 19", owner: 6 },
        { name: "Gunsmith - Part 20", owner: 6 },
        { name: "Gunsmith - Part 21", owner: 6 },
        { name: "Gunsmith - Part 22", owner: 6 },
        { name: "Gunsmith - Part 23", owner: 6 },
        { name: "Gunsmith - Part 24", owner: 6 },
        { name: "Signal - Part 1", owner: 6 },
        { name: "Insider", owner: 6 },
        { name: "Signal - Part 2", owner: 6 },
        { name: "Scout", owner: 6 },
        { name: "Surplus Goods", owner: 6 },
        { name: "Back Door", owner: 6 },
        { name: "Signal - Part 3", owner: 6 },
        { name: "Signal - Part 4", owner: 6 },
        { name: "Farming - Part 1", owner: 6 },
        { name: "Farming - Part 2", owner: 6 },
        { name: "Farming - Part 3", owner: 6 },
        { name: "Farming - Part 4", owner: 6 },
        { name: "Bad Habit", owner: 6 },
        { name: "Psycho Sniper", owner: 6 },
        { name: "A Shooter Born in Heaven", owner: 6 },
        { name: "Fertilizers", owner: 6 },
        { name: "Import", owner: 6 },
        { name: "Chemistry Closet", owner: 6 },
        { name: "Calibration", owner: 6 },
        { name: "The Courier", owner: 6 },
        { name: "Corporate Secrets", owner: 6 },
        { name: "Energy Crisis", owner: 6 },
        { name: "Broadcast - Part 1", owner: 6 },
        { name: "Broadcast - Part 2", owner: 6 },
        { name: "Watching You", owner: 6 },
        { name: "Surveillance", owner: 6 },
        { name: "Network Provider - Part 1", owner: 6 },
        { name: "Network Provider - Part 2", owner: 6 },
        { name: "Assessment - Part 1", owner: 6 },
        { name: "Assessment - Part 2", owner: 6 },
        { name: "Assessment - Part 3", owner: 6 },
        { name: "Key to the Tower", owner: 6 },
        { name: "Knock-Knock", owner: 6 },
        { name: "Getting Acquainted", owner: 6 },
        { name: "Make Amends - Buyout", owner: 6 },
        { name: "Make Amends - Equipment", owner: 6 },
        { name: "Make Amends - Security", owner: 6 },
        { name: "Make Amends - Sweep Up", owner: 6 },
        { name: "Make Amends", owner: 6 },
        { name: "Only Business", owner: 7 },
        { name: "Audit", owner: 7 },
        { name: "Ballet Lover", owner: 7 },
        { name: "Audiophile", owner: 7 },
        { name: "Harley Forever", owner: 7 },
        { name: "Make ULTRA Great Again", owner: 7 },
        { name: "Big Sale", owner: 7 },
        { name: "A Fuel Matter", owner: 7 },
        { name: "Inventory Check", owner: 7 },
        { name: "The Blood of War - Part 1", owner: 7 },
        { name: "Dressed to Kill", owner: 7 },
        { name: "Gratitude", owner: 7 },
        { name: "Hot Delivery", owner: 7 },
        { name: "Scavenger", owner: 7 },
        { name: "Out of Time", owner: 7 },
        { name: "Sales Night", owner: 7 },
        { name: "Database - Part 1", owner: 7 },
        { name: "Database - Part 2", owner: 7 },
        { name: "Minibus", owner: 7 },
        { name: "Sew it Good - Part 1", owner: 7 },
        { name: "The Blood of War - Part 2", owner: 7 },
        { name: "The Blood of War - Part 3", owner: 7 },
        { name: "Living High is Not a Crime - Part 2", owner: 7 },
        { name: "Sew it Good - Part 2", owner: 7 },
        { name: "The Key to Success", owner: 7 },
        { name: "No Fuss Needed", owner: 7 },
        { name: "The Stylish One", owner: 7 },
        { name: "Supervisor", owner: 7 },
        { name: "Sew it Good - Part 3", owner: 7 },
        { name: "Living High is Not a Crime - Part 1", owner: 7 },
        { name: "Sew it Good - Part 4", owner: 7 },
        { name: "Charisma Brings Success", owner: 7 },
        { name: "Textile - Part 1", owner: 7 },
        { name: "Textile - Part 2", owner: 7 },
        { name: "Long Line", owner: 7 },
        { name: "Booze", owner: 7 },
        { name: "Acquaintance", owner: 8 },
        { name: "The Survivalist Path - Unprotected but Dangerous", owner: 8 },
        { name: "The Survivalist Path - Thrifty", owner: 8 },
        { name: "The Delicious Sausage", owner: 8 },
        { name: "Cease Fire!", owner: 8 },
        { name: "The Survivalist Path - Zhivchik", owner: 8 },
        { name: "The Survivalist Path - Wounded Beast", owner: 8 },
        { name: "The Survivalist Path - Tough Guy", owner: 8 },
        { name: "Courtesy Visit", owner: 8 },
        { name: "Nostalgia", owner: 8 },
        { name: "The Survivalist Path - Cold Blooded", owner: 8 },
        { name: "The Survivalist Path - Junkie", owner: 8 },
        { name: "The Survivalist Path - Eagle-Owl", owner: 8 },
        { name: "The Survivalist Path - Combat Medic", owner: 8 },
        { name: "Ambulance", owner: 8 },
        { name: "The Huntsman Path - Secured Perimeter", owner: 8 },
        { name: "Reserve", owner: 8 },
        { name: "The Huntsman Path - Forest Cleaning", owner: 8 },
        { name: "The Huntsman Path - Administrator", owner: 8 },
        { name: "Slaughterhouse", owner: 8 },
        { name: "The Huntsman Path - Controller", owner: 8 },
        { name: "The Huntsman Path - Evil Watchman", owner: 8 },
        { name: "Fishing Place", owner: 8 },
        { name: "The Huntsman Path - Trophy", owner: 8 },
        { name: "The Huntsman Path - Justice", owner: 8 },
        { name: "The Huntsman Path - Sellout", owner: 8 },
        { name: "The Huntsman Path - Woods Keeper", owner: 8 },
        { name: "Hunting Trip", owner: 8 },
        { name: "The Huntsman Path - Factory Chief", owner: 8 },
        { name: "The Huntsman Path - Eraser - Part 1", owner: 8 },
        { name: "The Huntsman Path - Eraser - Part 2", owner: 8 },
        { name: "The Tarkov Shooter - Part 1", owner: 8 },
        { name: "The Tarkov Shooter - Part 2", owner: 8 },
        { name: "The Tarkov Shooter - Part 3", owner: 8 },
        { name: "The Tarkov Shooter - Part 4", owner: 8 },
        { name: "The Tarkov Shooter - Part 5", owner: 8 },
        { name: "The Tarkov Shooter - Part 6", owner: 8 },
        { name: "The Tarkov Shooter - Part 7", owner: 8 },
        { name: "The Tarkov Shooter - Part 8", owner: 8 },
        { name: "Shady Business", owner: 8 },
        { name: "The Huntsman Path - Sadist", owner: 8 },
        { name: "Hunter", owner: 8 },
        { name: "Pest Control", owner: 8 },
        { name: "Swift One", owner: 8 },
        { name: "The Huntsman Path - Relentless", owner: 8 },
        { name: "The Hermit", owner: 8 },
        { name: "The Huntsman Path - Outcasts", owner: 8 },
        { name: "Stray Dogs", owner: 8 },
        { name: "Broadcast - Part 3", owner: 8 },
        { name: "Broadcast - Part 4", owner: 8 },
        { name: "Broadcast - Part 5", owner: 8 },
        { name: "The Huntsman Path - Big Game", owner: 8 },
      ],
    };
  },
};
</script>
